import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import {SignInButton,useUser, SignOutButton} from "@clerk/nextjs";

export default function Home() {
  const user = useUser();


  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main>
        {!user.isSignedIn && <SignInButton/>}{!!user.isSignedIn && <SignOutButton/>}
        

        </main>
      
    </>
  );
}
